// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kasdexrrbfaivdvnwvge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imthc2RleHJyYmZhaXZkdm53dmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzIxMzMsImV4cCI6MjA1NDg0ODEzM30.F1dr3bUdb7YUXgMVzB1Ci_07B9-GOf6jY4msOLpzuB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);